import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>EFT Collaberative Maps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Hello, world.
    </div>
  );
}
