name: Test
'on': [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Start App
        run: |
          yarn
          NODE_ENV=test yarn build
          NODE_ENV=test yarn start &

      - name: Unit Tests
        run: yarn test --watchAll=false

      - name: Cypress run
        uses: cypress-io/github-action@v2
