name: E2E Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Start App
        run: |
          yarn
          NODE_ENV=test yarn build
          NODE_ENV=test yarn start &
      - name: Unit Tests
        run: |
          yarn test --watchAll=false
      - name: E2E Tests
        uses: cypress-io/github-action@v2
